<a href="https://colab.research.google.com/github/Vitaly-lv/DS2022/blob/main/NLP2_HW_LeontevVV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Реализовать tfidf  для quora.txt (на примере 50 строк)

In [ ]:
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer


In [ ]:
# выгружаем датасет:
!wget https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 -O ./quora.txt -nc

--2022-12-08 12:39:00--  https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.5.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.5.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/dl/obaitrix9jyu84r/quora.txt [following]
--2022-12-08 12:39:00--  https://www.dropbox.com/s/dl/obaitrix9jyu84r/quora.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc4f28e745ace1ef090dd0ad1a50.dl.dropboxusercontent.com/cd/0/get/ByN136Po80TCbCAnUCTpvHSK8Nz7FPSeOGnfP90Kc6nvxzV4gwaZR7R656GiPsEVz_KeUCaR6oTHlY95qbvODRAfNhVmuSpoJw-C_PvJI7yv8pPv4Yt-gVod64fgDYw46QKmnK8vFObHbpea9tFjWSdoJ1lVGftbr_biL3G-MjdYkA/file?dl=1# [following]
--2022-12-08 12:39:00--  https://uc4f28e745ace1ef090dd0ad1a50.dl.dropboxusercontent.com/cd/0/get/ByN136Po80TCbCAnUCTpvHSK8Nz7FPSeOGnfP90Kc6nvxzV4gwaZR7R656GiPsEVz_KeUCaR6oTHlY95qbvODRA

In [ ]:
data = list(open("./quora.txt", encoding="utf-8"))
data[50]

"What TV shows or books help you read people's body language?\n"

In [ ]:
data_sample = data[:50]

In [ ]:
#using the count vectorizer
count = CountVectorizer()
word_count=count.fit_transform(data_sample)
print(word_count)

  (0, 37)	1
  (0, 101)	1
  (0, 26)	1
  (0, 265)	2
  (0, 161)	1
  (0, 82)	1
  (0, 80)	1
  (0, 233)	1
  (0, 210)	1
  (0, 131)	1
  (0, 190)	1
  (0, 12)	1
  (0, 110)	1
  (0, 25)	1
  (1, 257)	1
  (1, 14)	1
  (1, 218)	1
  (1, 252)	1
  (1, 236)	1
  (1, 182)	1
  (1, 88)	1
  (1, 93)	1
  (1, 6)	1
  (2, 261)	2
  (2, 256)	1
  :	:
  (47, 14)	1
  (47, 261)	1
  (47, 231)	1
  (47, 124)	1
  (47, 35)	1
  (47, 237)	1
  (47, 50)	1
  (47, 22)	1
  (48, 236)	1
  (48, 262)	1
  (48, 64)	1
  (48, 94)	1
  (48, 102)	1
  (48, 249)	1
  (48, 33)	1
  (48, 193)	1
  (49, 11)	1
  (49, 211)	1
  (49, 169)	1
  (49, 29)	1
  (49, 56)	1
  (49, 179)	1
  (49, 163)	1
  (49, 221)	1
  (49, 116)	1


In [ ]:
print(word_count.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count)
df_idf = pd.DataFrame(tfidf_transformer.idf_, index=count.get_feature_names(),columns=["idf_weights"])

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
#inverse document frequency
df_idf.sort_values(by=['idf_weights'])

idf_weights
the         2.041454
is          2.159237
how         2.159237
what        2.223775
can         2.446919
...              ...
goldman     4.238678
graphic     4.238678
great       4.238678
guy         4.238678
zotac       4.238678

[274 rows x 1 columns]

In [ ]:
#tfidf
tf_idf_vector=tfidf_transformer.transform(word_count)
feature_names = count.get_feature_names()
first_document_vector=tf_idf_vector[1]
df_tfifd= pd.DataFrame(first_document_vector.T.todense(), index=feature_names, columns=["tfidf"])
df_tfifd.sort_values(by=["tfidf"],ascending=False)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


tfidf
fast       0.375678
ways       0.375678
addiction  0.375678
some       0.375678
food       0.375678
...             ...
from       0.000000
george     0.000000
get        0.000000
girls      0.000000
zotac      0.000000

[274 rows x 1 columns]

2. Для BoW, TF-IDF и датасета quora.txt (50 строк) найти самые схожие объекты (косинусное расстояние).

2.1 BoW

In [ ]:
#Установка нужных пакетов
!pip install --upgrade nltk gensim bokeh umap-learn

import itertools
import string

import numpy as np
import umap
from nltk.tokenize import WordPunctTokenizer

from numpy import dot
from numpy.linalg import norm


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 24.1 MB 1.1 MB/s 
     |████████████████████████████████| 16.4 MB 11.0 MB/s 
     |████████████████████████████████| 88 kB 5.7 MB/s 
     |████████████████████████████████| 55 kB 2.7 MB/s 
     |████████████████████████████████| 295 kB 66.9 MB/s 
     |████████████████████████████████| 1.1 MB 50.5 MB/s 
  Created wheel for umap-learn: filename=umap_learn-0.5.3-py3-none-any.whl size=82829 sha256=2610a23067d9e51ddefbfbed9f800fe1905b4f7f5e1cbdf0fdef3ff17bc612af
  Stored in directory: /root/.cache/pip/wheels/a9/3a/67/06a8950e053725912e6a8c42c4a3a241410f6487b8402542ea
  Created wheel for pynndescent: filename=pynndescent-0.5.8-py3-none-any.whl size=55513 sha256=956bf4b74f8e56867244f817f9449e800cb002ed333666564daa15c75f6a2d9c
  Stored in directory: /root/.cache/pip/wheels/1c/63/3a/29954bca1a27ba100ed8c27973a78cb71b43dc67aed62e80c3
Successfully built umap-

In [ ]:
tokenizer = WordPunctTokenizer()

In [ ]:
data_tok = []
for i in range(len(data_sample)): 
  data_tok.append(tokenizer.tokenize(data_sample[i].lower()))

In [ ]:
def vectorize(tokens):
    vector=[]
    for w in filtered_vocab:
        vector.append(tokens.count(w))
    return vector

stopwords=["os","at","of","s","i","in","a","to","jk", "an", "ve","c","rr",
           "vm","j","as","the"]

special_char=["2","130","960",":",",","?","-", "/","2015",".","'"]

In [ ]:
# Формирование словаря
vocab = []
for i in data_tok:
  for j in i:
    vocab.append(j)

vocab = list(set(vocab))

In [ ]:
# удаление стоп-слов и спец.символов
filtered_vocab=[]
for w in vocab: 
    if w not in stopwords and w not in special_char: 
        filtered_vocab.append(w)

In [ ]:
# формирование векторов
vectors =[]
for i in data_tok:
    vector_i = vectorize(i)
    vectors.append(vector_i)
print(vectors)

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
# нахождение подобных векторов через косинусное расстояние

cos = dict()
for i, a in enumerate(vectors):
    for u, b in enumerate(vectors):
        if i != u:
            cos_sim = dot(a, b)/(norm(a)*norm(b))
            cos[(i,u)] = cos_sim
pair = None
for x in cos:
    if cos.get(x) == max(cos.values()):
        print(x)
        pair = x
        break
for x in pair:
    print(data_tok[x])

(8, 27)
['what', 'is', 'your', 'review', 'of', 'osquery', '?']
['what', 'is', 'your', 'review', 'of', 'ipad', 'mini', '2', '?']


2.2 TD-IDF

In [ ]:
# для формирование списка векоров возьмем word_count из 1 задания
tfidf_vectors = word_count.toarray()

In [ ]:
# нахождение подобных векторов через косинусное расстояние
cos = dict()
for i, a in enumerate(tfidf_vectors):
    for u, b in enumerate(tfidf_vectors):
        if i != u:
            cos_sim = dot(a, b)/(norm(a)*norm(b))
            cos[(i,u)] = cos_sim
pair = None
for x in cos:
    if cos.get(x) == max(cos.values()):
        print(x)
        pair = x
        break
for x in pair:
    print(data_tok[x])

(8, 27)
['what', 'is', 'your', 'review', 'of', 'osquery', '?']
['what', 'is', 'your', 'review', 'of', 'ipad', 'mini', '2', '?']


Через BoW и TFIDF найдены одни  и те же наиболее совпадающие предложения.